import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-white">
          <div className="h-10 border-b text-justify border-black border-solid">
            <Navbar />
          </div>
          <div className="h-[cal(100vh - 40px)] 8px-2 sm:px-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
