import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import TransitionProvider from "./components/TransitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-10 border-b text-justify  z-50 bg-white border-black border-solid">
          <Navbar />
        </div>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
